# Generated by Django 4.2.16 on 2025-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_auto_20250415_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_route',
            name='route',
            field=models.CharField(default='Unknown Route', max_length=100),
        ),
    ]
