# Generated by Django 4.2.16 on 2025-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_alter_add_route_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_route',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
